site_name: MITRE Settingslogic
site_description: A simple and straightforward Ruby settings solution with YAML configuration
site_author: MITRE Corporation
site_url: https://mitre.github.io/settingslogic/

repo_name: mitre/settingslogic
repo_url: https://github.com/mitre/settingslogic
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.action.edit
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quick-start.md
    - Migration from v2.x: migration.md
  - Usage:
    - Basic Usage: basic-usage.md
    - YAML Configuration: yaml-configuration.md
    - Security Settings: SECURITY.md
    - Advanced Features: advanced.md
  - Development:
    - Contributing: CONTRIBUTING.md
    - Testing: testing.md
    - Release Process: release-process.md
    - Coverage Analysis: development/coverage-analysis.md
    - Fixes Implemented: development/fixes-implemented.md
    - Gem Publishing: development/gem-publishing.md
    - Test Reorganization: development/test-reorganization.md
  - Project:
    - About:
      - Roadmap: ROADMAP.md
      - Changelog: CHANGELOG.md
      - Security Policy: SECURITY.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - License: LICENSE.md
      - Notice: NOTICE.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mitre/settingslogic
  version:
    provider: mike