name: CI

on:
  push:
    branches: [ master, main, ruby-3-compatibility ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
          - 'head'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems
    
    - name: Run tests
      run: bundle exec rspec
    
    - name: Run Rubocop
      run: bundle exec rubocop
      continue-on-error: true # Don't fail on style issues for now
  
  test-with-rails:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Test with various Rails versions
          # NOTE: Ruby 2.7 + Rails 6.1 excluded due to zeitwerk dependency conflict
          #       (zeitwerk > 2.6.18 requires Ruby >= 3.2, but Rails 6.1 requires zeitwerk ~> 2.3)
          #       This is a Rails/zeitwerk issue, not a settingslogic issue
          - ruby-version: '3.0'
            rails-version: '7.0'
          - ruby-version: '3.1'
            rails-version: '7.0'
          - ruby-version: '3.2'
            rails-version: '7.1'
          - ruby-version: '3.3'
            rails-version: '7.1'
          - ruby-version: '3.4'
            rails-version: '8.0'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    
    - name: Install Rails ${{ matrix.rails-version }}
      run: |
        gem install rails -v "~> ${{ matrix.rails-version }}.0"
        bundle install
    
    - name: Run tests with Rails
      run: bundle exec rspec