name: Release on Tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write  # Required for OIDC trusted publishing

env:
  RUBY_VERSION: '3.2'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for changelog
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          
      - name: Run tests
        run: bundle exec rspec
        
      - name: Run security audit
        run: |
          gem install bundler-audit
          bundler-audit check --update
          
      - name: Run linting
        run: bundle exec rubocop
        
      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## mitre-settingslogic v${{ steps.version.outputs.VERSION }}
            
            See [CHANGELOG.md](https://github.com/mitre/settingslogic/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false
          
      - name: Configure RubyGems credentials
        uses: rubygems/configure-rubygems-credentials@v1.0.0
          
      - name: Build and publish gem
        run: |
          gem build settingslogic.gemspec
          gem push mitre-settingslogic-*.gem